<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>10</LangVersion>
    <AssemblyName>SmartSystemMenu</AssemblyName>
    <RootNamespace>SmartSystemMenu</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Management" />
    <Reference Include="UIAutomationClient" />
    <Reference Include="UIAutomationTypes" />
  </ItemGroup>
</Project>